### ISSUE TITLE
Fix status is code 200

### ISSUE THREAD

**Issue by gustavocondec** [gusgcc/backend-sist-distribuidos#1]
https://github.com/gusgcc/backend-sist-distribuidos/blob/a7bbff6bf341e51aeb05763f69cd0031c76c7e58/src/controllers/publicacionController.js#L83

Deberia ser : res.status(200).json({ mensaje: "Publicacion eliminada de forma correcta" })

**Comment by ronald9715** [comment]
Issue solucionado

**Comment by gustavocondec** [comment]
Gracias
